version: "3"
services:
  frontend:
    build:
      context: ./FRONTEND/tutorchat-adaptation-its
    environment:
      - VITE_API_BASE_URL="http://backend:8000"
      - VITE_WS_BASE_URL="ws://backend:8000"
      - VITE_PUBLIC_URL="http://backend:8000/"
    ports:
      - "127.0.0.1:3000:3000"
  backend:
    build:
      context: ./BACKEND
    environment:
      - REDIS_HOST=nosql
    ports:
      - "127.0.0.1:8000:8000"
  nosql:
    image: redis:7.4.2
    ports:
      - "127.0.0.1:6379:6379"